# 1. インストールとインポート

In [13]:
!pip install numpy

In [2]:
import numpy as np

# 2. 配列の作成

## 2.1 1次元配列

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

## 2.2 2次元配列

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 3. 配列の操作

## 3.1 配列の形状

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape
# -> (2, 3)

(2, 3)

## 3.2 配列のリシェイプ

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)
# -> array([[1, 2, 3],
#            [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

# 4. 数学的演算

## 4.1 要素ごとの加算

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
# -> array([5, 7, 9])

array([5, 7, 9])

## 4.2 要素ごとの乗算

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b
# -> array([ 4, 10, 18])

array([ 4, 10, 18])

# 5. 統計関数

## 5.1 平均値

In [9]:
arr = np.array([1, 2, 3, 4, 5])
np.mean(arr)
# -> 3.0

3.0

## 5.2 分散

In [10]:
arr = np.array([1, 2, 3, 4, 5])
np.var(arr)
# -> 2.0

2.0

# 6. 線形代数

## 6.1 行列の積

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.dot(a, b)
# -> array([[19, 22],
#           [43, 50]])

array([[19, 22],
       [43, 50]])

## 6.2 逆行列

In [12]:
a = np.array([[1, 2], [3, 4]])
np.linalg.inv(a)
# -> array([[-2. ,  1. ],
#           [ 1.5, -0.5]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])